### ISSUE TITLE
Test suite list does not get updated after changing files in the volume

### ISSUE THREAD

**Issue by eleazar-araujo** [etf-validator/etf-webapp-docker#16]
Once a container is started, and a bind mount is specified the volume gets created in the specified folder. However after updating some of the files there, the changes are not being reflected on the web-app
For example, after a container is started, creating a folder in the projects subfolder as indicated in the section 4.1 of
http://docs.etf-validator.net/v2.0/Admin_manuals/index.html#_installation
doesn't have any effect on the app, even though in the above mentioned docs it's indicated that `The framework will automatically load the Executable Test Suites after a short time and list the Test Suites in the Start Tests view.`

**Comment by jonherrmann** [comment]
Is there any entry in the log file? Which Executable Test Suites have you copied into this subfolder and are the IDs of the Executable Test Suites unique?

**Comment by eleazar-araujo** [comment]
The Ids are unique. The executable test suite is a custom one generated from another external system, but it complies correctly with the syntax because replacing one of the existing test with this custom one delivers the expected result.

Does the ID of the Executable Test Suite needs to be manually copied to the v4_uuids.txt files?
By the log file you mean the docker container logs?

**Comment by eleazar-araujo** [comment]
What could be the cause of the following error at startup?

```
2018-06-22 08:54:29.597:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@4520ebad{/etf-webapp,[file:///tmp/jetty/jetty-0.0.0.0-8080-etf-webapp.war-_etf-webapp-any-5052137577174822650.dir/webapp/, jar:file:///tmp/jetty/jetty-0.0.0.0-8080-etf-webapp.war-_etf-webapp-any-5052137577174822650.dir/webapp/WEB-INF/lib/springfox-swagger-ui-2.6.1.jar!/META-INF/resources],STARTING}{/etf-webapp.war}
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'etsController': Unsatisfied dependency expressed through field 'testDriverController'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testDriverController': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
```

The <testDriver> reference for my test file is just as in the other files. An according to the ETF documentation:
`The element etf:testDriver references the test driver for BaseX. The current test driver has a fixed identifier "EID4dddc9e2-1b21-40b7-af70-6a2d156ad130".`

**Comment by jonherrmann** [comment]
The origin of the error is not shown in your log snippet. Please post the entire log file (and remove sensitive information!). Preferably attach the log file.

**Comment by eleazar-araujo** [comment]
The problem was solved. Thanks a lot for the support
